

default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: mine_sweeper_graphql_api_development


test:
  <<: *default
  database: mine_sweeper_graphql_api_test

production:
  <<: *default
  database: mine_sweeper_graphql_api_production